# 登录
username_inputbox = '//*[@id="loginForm"]/div[2]/input'
password_inputbox = '//*[@id="j_password_show_id"]'
submit_button = '//*[@id="loginForm"]/div[6]/input'
login_success = '//*[@id="Hui-userbar"]/ul/li/a/span'
login_fail = '//*[@id="loginForm"]/div[1]/span'
logout_icon ='//*[@id="Hui-userbar"]/ul'
logout_button = '//*[@id="Hui-userbar"]/ul/li/ul/li'
collection_icon ='/html/body/div/div[5]/div/div/div/div/div[3]'
collection_verify = '/html/body/header/div[2]/div/a[2]'
collection_verify1 = '/html/body/div/div[1]'
welcome_frame = '//*[@id="iframe_box"]/div/iframe'
authCode_loc = '//*[@id="loginForm"]/div[4]/input'

# 我的案件
collection_management = '/html/body/aside/div/dl[1]/dt'
myCase_iFrame_loc = '//*[@id="iframe_box"]/div[2]/iframe'
myCase = '/html/body/aside/div/dl[1]/dd/ul/li[1]'
click_current_page = '//*[@id="searchForm"]/div/div[5]/div[2]/div/div[1]'
myCaseList_verify = '//*[@id="mycase"]/tbody/tr[1]/td[2]'
next_button = '//*[@id="pag_wrap"]/div[2]/a[8]'
previous_button = '//*[@id="pag_wrap"]/div[2]/a[1]'
secondPage_verify = '//*[@id="mycase"]/tbody/tr[1]/td[2]'

# 全文检索
gloableSearch_button = '//*[@id="gloable-form"]/div[7]/input'
contactsPhone_loc = '//*[@id="contactsPhone"]'
idCard_loc = '//*[@id="custIdcard"]'
accountNo_loc = '//*[@id="custAccountNo"]'
cardNo_loc = '//*[@id="custCardNo"]'
address_loc = '//*[@id="billingAddress"]'
custName_loc = '//*[@id="custName"]'
sarchNull_verify_loc = '//*[@id="layui-layer1"]/div'
click_more = '//*[@id="isShowMoreTrue"]'
click_search_result = '//*[@id="mycase"]/tbody/tr[1]'
search_phone_verify = '//*[@id="CaseInfoExtend"]/tbody/tr[5]/td[4]'
no_search_result = '/html/body/div/div[1]/span[1]'
searchIdCard_verify = '//*[@id="mycase"]/tbody/tr/td[3]'
searchAccountNo_verify = '//*[@id="mycase"]/tbody/tr[1]/td[16]'
searchCardNo_verify = '//*[@id="mycase"]/tbody/tr[1]/td[2]'
searchAddress_verify = '/html/body/div[1]/div[2]/div/div[2]/table[1]/tbody/tr[12]/td[4]'

# 我的案件
trustorCheckbox = '//*[@id="searchForm"]/div/div[1]/div[1]/div/div[2]/span'
trustorSelect = '//*[@id="searchForm"]/div/div[1]/div[1]/div/div[2]/span/select'
searchButton = '//*[@id="searchForm"]/div/div[7]/div/div/div[2]/button[1]'
clickAnyCase = '//*[@id="mycase"]/tbody/tr[10]'
trustorVerify_loc = '/html/body/div[1]/div[2]/div/div[2]/table[1]/tbody/tr[1]/td[4]'
resultVerify_loc = '/html/body/div[3]/div[2]/span[1]'
caseTypeSelect_loc = '//*[@id="searchForm"]/div/div[1]/div[3]/div/div[2]/span/select'
colorStatusSelect_loc = '//*[@id="searchForm"]/div/div[2]/div[1]/div/div[2]/span/select'
collectionStatusSelect_loc = '//*[@id="searchForm"]/div/div[2]/div[2]/div/div[2]/span/select'
collectionStatusVerify_loc = '//*[@id="mycase"]/tbody/tr/td[12]'
repaymentSelect_loc = '//*[@id="searchForm"]/div/div[2]/div[3]/div/div[2]/span/select'
collectionAreaSelect_loc = '//*[@id="searchForm"]/div/div[3]/div[4]/div/div[2]/div/span/select'
commissionDateStart_loc = '//*[@id="searchForm"]/div/div[1]/div[4]/div/div[2]/div/div[1]/input'
commissionDateEnd_loc = '//*[@id="searchForm"]/div/div[1]/div[4]/div/div[2]/div/div[2]/input'
LFUDateStart_loc = '//*[@id="searchForm"]/div/div[1]/div[5]/div/div[2]/div/div[1]/input'
LFUDateEnd_loc = '//*[@id="searchForm"]/div/div[1]/div[5]/div/div[2]/div/div[2]/input'
repaymentDateStart_loc = '//*[@id="searchForm"]/div/div[2]/div[4]/div/div[2]/div/div[1]/input'
repaymentDateEnd_loc = '//*[@id="searchForm"]/div/div[2]/div[4]/div/div[2]/div/div[2]/input'
entrustAmtMin_loc = '//*[@id="entrustAmt"]/div[1]/input'
entrustAmtMax_loc = '//*[@id="entrustAmt"]/div[2]/input'
entrustAmtMinWrong_loc = '//*[@id="layui-layer1"]/div'
entrustAmtMaxWrong_loc = '//*[@id="layui-layer2"]/div'
phoneNo_loc = '//*[@id="search_contactsPhone"]'
overdueDaysMin_loc = '//*[@id="searchForm"]/div/div[3]/div[2]/div/div[2]/div/div[1]/input'
overdueDaysMax_loc = '//*[@id="searchForm"]/div/div[3]/div[2]/div/div[2]/div/div[2]/input'
accountAge_loc = '//*[@id="search_overdueReceivables"]'
accountAgeClick_loc = '//*[@id="select2-search_overdueReceivables-result-gsu4-M2"]'
accountAgeClick1_loc = '//*[@id="select2-search_overdueReceivables-result-gsu4-M2"]'
accountAgeVerify_loc = '//*[@id="mycase"]/tbody/tr/td[5]'
searchAddress_loc = '//*[@id="searchForm"]/div/div[4]/div/div/div[2]/input'
searchName_loc = '//*[@id="searchForm"]/div/div[5]/div[1]/div/div[2]/div/div/textarea'
searchCardNo_loc = '//*[@id="searchForm"]/div/div[5]/div[2]/div/div[2]/div/div/textarea'
searchSerialNo_loc = '//*[@id="searchForm"]/div/div[5]/div[3]/div/div[2]/textarea'
searchBatchNo_loc = '//*[@id="search_batchNo"]'
searchIdCard_loc = '//*[@id="searchForm"]/div/div[6]/div[2]/div/div[2]/textarea'
searchClearBtn_loc = '//*[@id="searchForm"]/div/div[7]/div/div/div[2]/button[2]'
searchSelectCase_loc = '//*[@id="mycase"]/tbody/tr[1]/td[1]/input'
updateStatusBtn_loc = '/html/body/div[3]/div[1]/div[2]/button[2]'
updateStatusSelect_loc = '//*[@id="updateStatus"]/span/select'
updateStatusOKBtn_loc = '//*[@id="layui-layer1"]/div[3]/a[1]'
updateStatusVerify_loc = '//*[@id="mycase"]/tbody/tr[1]/td[12]'
